[web]
ec2-web ansible_host=3.253.21.198 ansible_user=ubuntu ansible_ssh_private_key_file=~/.ssh/tech257.pem

[db]
ec2-db ansible_host=63.33.209.72 ansible_user=ubuntu ansible_ssh_private_key_file=~/.ssh/tech257.pem
